# Generated by Django 5.2.4 on 2025-07-23 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SobreMi',
        ),
        migrations.AddField(
            model_name='perfil',
            name='sobre_mi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
