# Generated by Django 5.2.4 on 2025-07-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_tecnologia_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
