# Generated by Django 5.2.4 on 2025-07-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_educacion_publicado_experiencia_publicado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educacion',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='tecnologia',
            name='publicado',
            field=models.BooleanField(default=True),
        ),
    ]
